#!/bin/bash

getColor() {
  case "$1" in
    black) color="0;30m";;
    red) color="1;31m";;
    green) color="1;32m";;
    blue) color="1;34m";;
    brown) color="0;33m";;
    yellow) color="1;33m";;
    white) color="1;37m";;
  esac
  echo "\033[$color"
}

# DEFAULT CONFIG PARAMETERS
color=$(getColor yellow)
character=■
granularity=50
append_numeric_after_progressbar=true

if [ -p /dev/stdin ]; then
  value=$(cat /dev/stdin | tr -d % | tr -d '\n')
else
  value=$(echo $1 | tr -d %)
fi

#dd if=/dev/zero of=DiskOS.img bs=512 count=93750 status=progress  | grep 'bytes' | awk '{print $1}'

#for (( value = 0; value <= 100; value++)) do
  let step_size=100/$granularity
  let num_of_progress_items=$value/$step_size

  if [ "$color" ]
  then
    printf $color
  fi

  printf "Progress: "
  printf '|'
  for i in $(seq 0 $granularity)
  do
    [[ $i -le $num_of_progress_items ]] && printf "$character" || printf ' '
  done  

  printf '|'

  if [ "$allow_more_than_max" = true ] && [ $num_of_progress_items -gt $granularity ]
  then
    let num_of_excess_items=$num_of_progress_items-$granularity
    for i in $(seq 1 $num_of_excess_items)
    do
      printf $character
    done  
  fi

  if $append_numeric_after_progressbar
  then
    printf ' %d%%' $value
  fi 

  eval "tput sgr0" # reset color
  echo -ne "\r"
#done
#echo